/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    media: Media;
    'seo-redirects': SeoRedirect;
    'seo-audits': SeoAudit;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'seo-redirects': SeoRedirectsSelect<false> | SeoRedirectsSelect<true>;
    'seo-audits': SeoAuditsSelect<false> | SeoAuditsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'seo-tracking': SeoTracking;
  };
  globalsSelect: {
    'seo-tracking': SeoTrackingSelect<false> | SeoTrackingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Absolute URL. Defaults to site URL + slug when empty.
     */
    canonical?: string | null;
    robots?: {
      noindex?: boolean | null;
      nofollow?: boolean | null;
      noarchive?: boolean | null;
      nosnippet?: boolean | null;
      noimageindex?: boolean | null;
      notranslate?: boolean | null;
      unavailableAfter?: string | null;
    };
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    twitterSite?: string | null;
    twitterCreator?: string | null;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    hreflang?:
      | {
          language?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    includeInSitemap?: boolean | null;
    /**
     * 0–1, steps of 0.1
     */
    sitemapPriority?: number | null;
    sitemapChangefreq?: ('always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never') | null;
    schemaType?: ('' | 'Article' | 'Product' | 'FAQPage' | 'HowTo' | 'Event' | 'Recipe' | 'VideoObject') | null;
    faq?:
      | {
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional raw JSON-LD injected verbatim in addition to the generated schema.
     */
    rawJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-redirects".
 */
export interface SeoRedirect {
  id: string;
  /**
   * Source path, e.g. /old-page or /blog/:slug
   */
  from: string;
  /**
   * Destination path or absolute URL
   */
  to: string;
  statusCode?: ('301' | '302' | '307' | '308' | '410') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits".
 */
export interface SeoAudit {
  id: string;
  url: string;
  collection?: string | null;
  docId?: string | null;
  score?: number | null;
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'seo-redirects';
        value: string | SeoRedirect;
      } | null)
    | ({
        relationTo: 'seo-audits';
        value: string | SeoAudit;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        robots?:
          | T
          | {
              noindex?: T;
              nofollow?: T;
              noarchive?: T;
              nosnippet?: T;
              noimageindex?: T;
              notranslate?: T;
              unavailableAfter?: T;
            };
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        twitterSite?: T;
        twitterCreator?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        hreflang?:
          | T
          | {
              language?: T;
              url?: T;
              id?: T;
            };
        includeInSitemap?: T;
        sitemapPriority?: T;
        sitemapChangefreq?: T;
        schemaType?: T;
        faq?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        rawJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-redirects_select".
 */
export interface SeoRedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits_select".
 */
export interface SeoAuditsSelect<T extends boolean = true> {
  url?: T;
  collection?: T;
  docId?: T;
  score?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-tracking".
 */
export interface SeoTracking {
  id: string;
  ga4?: {
    enabled?: boolean | null;
    measurementId?: string | null;
    anonymizeIp?: boolean | null;
  };
  clarity?: {
    enabled?: boolean | null;
    projectId?: string | null;
  };
  plausible?: {
    enabled?: boolean | null;
    domain?: string | null;
    selfHostedUrl?: string | null;
  };
  postHog?: {
    enabled?: boolean | null;
    apiKey?: string | null;
    host?: string | null;
  };
  fathom?: {
    enabled?: boolean | null;
    siteId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-tracking_select".
 */
export interface SeoTrackingSelect<T extends boolean = true> {
  ga4?:
    | T
    | {
        enabled?: T;
        measurementId?: T;
        anonymizeIp?: T;
      };
  clarity?:
    | T
    | {
        enabled?: T;
        projectId?: T;
      };
  plausible?:
    | T
    | {
        enabled?: T;
        domain?: T;
        selfHostedUrl?: T;
      };
  postHog?:
    | T
    | {
        enabled?: T;
        apiKey?: T;
        host?: T;
      };
  fathom?:
    | T
    | {
        enabled?: T;
        siteId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}